# Generated by Django 5.0.6 on 2024-06-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancionAAprender',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
    ]
