# Generated by Django 5.0.6 on 2024-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_opiniones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiniones',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='cuerpo',
            field=models.TextField(max_length=500),
        ),
    ]
